name: linting, testing, building
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Staring Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run prod
      - name: linting typescript
        if: always()
        run: npm run eslint
      - name: linting css
        if: always()
        run: npm run stylelint
      - name: unit testing
        if: always()
        run: npm run test
      - name: build storybook
        if: always()
        run: npm run build:storybook
      - name: screenshot testing
        if: always()
        run: npm run loki:ci
